# Generated by Django 4.2.14 on 2024-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmarking',
            name='counter',
            field=models.BooleanField(default=False),
        ),
    ]
