# Generated by Django 4.2.14 on 2024-08-30 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_product_kpi_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarking',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_markings', to='warehouse.outcome'),
        ),
    ]
