# Generated by Django 4.2.14 on 2024-09-06 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_income_added_by_outcome_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='income',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='warehouse.income'),
            preserve_default=False,
        ),
    ]
